apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-ydnmglff 
  description: Secure Supply Chain Example for Python is an interpreted,  object-oriented, high-level programming language with dynamic semantics. This sample demonstrates software supply chain security functionalty using an advanced continuous integration pipeline covering building, CVE scanning, security scanning, signatures, attestations, SLSA provenance and SBOM along with Gitops-based continuous deployment.   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used tssc-gitops as the grouping
    argocd/app-selector: tssc/gitops=python-ydnmglff
    backstage.io/kubernetes-id: python-ydnmglff 
    backstage.io/techdocs-ref: dir:.
    dev.azure.com/project: shared-public
    dev.azure.com/build-definition: python-ydnmglff
    jfrog-artifactory/image-name: python-ydnmglff
  tags: ["python", "pip", "flask", "sscs", "sbom", "acs"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 